config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'information#about', as: 'about'
  get 'blog', to: 'information#blog', as: 'blog'

  get 'contact', to: 'more_info#contact', as: 'contact'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  def about
  end

  def blog
  end
end

app/controllers/more_info_controller.rb
class MoreInfoController < ApplicationController
  def contact
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @name = "Simon"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/information/about.html.erb
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/information/blog.html.erb
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar">
      <div class="nav">
        <div class="nav-item">
          <%= link_to 'Home', root_path, class: 'anchor active' %>
        </div>
        <div class="nav-item">
          <%= link_to 'About', about_path, class: 'anchor' %>
        </div>
        <div class="nav-item">
          <%= link_to 'Blog', blog_path, class: 'anchor' %>
        </div>
        <div class="nav-item">
          <%= link_to 'Contact', contact_path, class: 'anchor' %>
        </div>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/layouts/more_info.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <title>Document</title>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/more_info/contact.html.erb
<h1>Formulario de contacto</h1>

app/views/welcome/index.html.erb
<h1>Hola <%= @name %></h1>